### PR TITLE
Autentication with using gem 'devise'

### PR DESCRIPTION
**Pull request by Laguna1**
In these projects, we worked on the implementation of authentication systems.

Users can: 
register;
sign in if already registered; 
create messages when already logged in;
see the authors of other posts;
sign out.

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
# Changes Required.

## Hi team :wave: 

Your project looks good. Just few updates to make.

- [x] Some of the view files in your **```layout folder```** have view logic in them. View related logic should be put in View helpers. Use this [link](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) as a guide.  

It would be nice if you create your post routes,  using **```resources :posts, only: [:new, :create, :index]```** 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

That's it, make these changes, then submit another code review form.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets implement linter checks for this project.
- [x] Some of the view files in your layout folder still have view logic in them. View related logic should be placed in View helpers(app/helpers/*_helper.rb).


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Laguna1** [comment]
We checked for errors with the 'Rubocop' and 'Stickler' and moved the logic to the helper directory.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, congratulations on fixing all but one of the comments made by the previous TSE :+1: 
We, however, have logic in our view file.
Kindly address the comments made by the previous TSE :+1: 

Kindly submit another code review once this is fixed
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Laguna1** [comment]
We fixed our logic in the post_helper from the view.

**Review by euqueme — APPROVED** [review]
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @Laguna1 and @chinweokwu :lollipop: :balloon: 

### You've done a great job with this project :1st_place_medal: :1st_place_medal: I absolutely loved the style you used, and your code is so professional it blew me away, please please continue coding like this and be proud of your work you may merge this branch is a yes for me congratulations! :tada: :tada: :tada: 

## [OPTIONAL]

- [ ] before merging please remove the link to your live demo because it's leading to a broken page you also have a broken link at the end of the images in your readme file, let's make it work or remove it from your project.

PROJECT STATUS: APPROVED! :heavy_check_mark:

**Pull request merged**
